#!/bin/bash

COMMAND=${1:-run}

if [ "$COMMAND" = "run" ]; then
    echo "Starting PocketBase dev server on http://0.0.0.0:8090..."
    go run . serve --http="0.0.0.0:8090"
elif [ "$COMMAND" = "build" ] || [ "$COMMAND" = "p" ]; then
    echo "Building Linux production binary..."
    GOOS=linux GOARCH=amd64 go build -o ledgeo
    echo "Done! Saved as: Ledgeo"
else
    echo "Usage: ./app {run|p}"
    exit 1
fi
